"""add walkthrough completed field to admin

Revision ID: a9a712f78df5
Revises: 388c7f0f64f8
Create Date: 2026-06-29 13:20:05.013059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a712f78df5'
down_revision: Union[str, Sequence[str], None] = '388c7f0f64f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('walkthrough_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'walkthrough_completed')
    # ### end Alembic commands ###
