"""add_performance_indexes

Revision ID: c475cfa56712
Revises: a58c126251bc
Create Date: 2026-06-22 23:23:31.856002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c475cfa56712'
down_revision: Union[str, Sequence[str], None] = 'a58c126251bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('uniq_org_device_id'), 'devices', type_='unique')
    op.create_index('ix_devices_faculty_id', 'devices', ['faculty_id'], unique=False)
    op.create_index('ix_devices_org_id', 'devices', ['organization_id'], unique=False)
    op.create_index('ix_location_events_event_time', 'location_events', ['event_time'], unique=False)
    op.create_index('ix_location_events_faculty_time', 'location_events', ['faculty_id', 'event_time'], unique=False)
    op.create_index('ix_location_events_org_id', 'location_events', ['organization_id'], unique=False)
    op.create_index('ix_notifications_org_role', 'notifications', ['organization_id', 'recipient_role'], unique=False)
    op.create_index('ix_notifications_recipient_id', 'notifications', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_recipient_id', table_name='notifications')
    op.drop_index('ix_notifications_org_role', table_name='notifications')
    op.drop_index('ix_location_events_org_id', table_name='location_events')
    op.drop_index('ix_location_events_faculty_time', table_name='location_events')
    op.drop_index('ix_location_events_event_time', table_name='location_events')
    op.drop_index('ix_devices_org_id', table_name='devices')
    op.drop_index('ix_devices_faculty_id', table_name='devices')
    op.create_unique_constraint(op.f('uniq_org_device_id'), 'devices', ['organization_id', 'id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    # ### end Alembic commands ###
