"""update_otp_verifications

Revision ID: daf886c1b6ff
Revises: c475cfa56712
Create Date: 2026-06-26 18:24:14.492922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf886c1b6ff'
down_revision: Union[str, Sequence[str], None] = 'c475cfa56712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('purpose', sa.String(length=20), nullable=False))
    op.add_column('otp_verifications', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('otp_verifications', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('otp_verifications', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('otp_verifications', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('otp_verifications', 'registration_data',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'registration_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('otp_verifications', 'used_at')
    op.drop_column('otp_verifications', 'expires_at')
    op.drop_column('otp_verifications', 'verified')
    op.drop_column('otp_verifications', 'attempt_count')
    op.drop_column('otp_verifications', 'purpose')
    # ### end Alembic commands ###
